services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hospital-analitica-app
    container_name: analitica-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - analitica

  db:
    image: postgres:14-alpine
    container_name: analitica-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: analitica
      POSTGRES_USER: analitica_app
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - analitica

  nginx:
    image: nginx:alpine
    container_name: analitica-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - analitica

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: hospital-analitica-app
    container_name: analitica-worker
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - ./:/var/www
    networks:
      - analitica

networks:
  analitica:
    driver: bridge

volumes:
  pgdata:
